#普通数据的配置   要空格
name: zhangsan

#对象的配置
person:
  name: zhangsan
  age: 18
  addr: beijing

#配置数据集合
city:
  - beijing
  - shanghai
  - chongqing

#配置数据，集合（对象数据）
student:
  - name: tom
    age: 18
    addr: shanghai
  - name: lucy
    age: 21
    addr: beijing


#Map配置
map:
    key1: value1
    key2: value2



server:
  port: 8080